param(
    [ValidateSet("compatible", "openai", "anthropic", "local", "mock")]
    [string]$Provider = "",
    [ValidateSet("deepseek", "qwen", "siliconflow", "custom")]
    [string]$CompatiblePreset = "",
    [string]$BaseUrl = "",
    [string]$Model = "",
    [string]$ApiKey = "",
    [switch]$EnableChroma,
    [switch]$DisableChroma,
    [switch]$Validate
)

$ErrorActionPreference = "Stop"
$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$EnvExamplePath = Join-Path $RepoRoot ".env.example"
$EnvPath = Join-Path $RepoRoot ".env"

function Read-DefaultedValue {
    param(
        [string]$Prompt,
        [string]$Default = ""
    )
    if ($Default) {
        $value = Read-Host "$Prompt [$Default]"
        if ([string]::IsNullOrWhiteSpace($value)) {
            return $Default
        }
        return $value.Trim()
    }
    return (Read-Host $Prompt).Trim()
}

function Read-SecretValue {
    param([string]$Prompt)
    $secure = Read-Host $Prompt -AsSecureString
    $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try {
        return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
    }
    finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
    }
}

function Read-EnvFile {
    param([string]$Path)
    $map = [ordered]@{}
    if (-not (Test-Path $Path)) {
        return $map
    }
    foreach ($line in Get-Content -Path $Path -Encoding UTF8) {
        if ($line -match '^\s*#' -or -not $line.Contains("=")) {
            continue
        }
        $parts = $line.Split("=", 2)
        $map[$parts[0].Trim()] = $parts[1]
    }
    return $map
}

function Write-EnvFile {
    param(
        [string]$Path,
        [System.Collections.Specialized.OrderedDictionary]$Values
    )
    $lines = @(
        "# Local API configuration generated by scripts/configure-api.ps1",
        "# This file is intentionally ignored by Git. Do not commit API keys.",
        ""
    )
    foreach ($key in $Values.Keys) {
        $lines += "$key=$($Values[$key])"
    }
    Set-Content -Path $Path -Value $lines -Encoding UTF8
}

function Set-Default {
    param(
        [System.Collections.Specialized.OrderedDictionary]$Values,
        [string]$Key,
        [string]$Value
    )
    if (-not $Values.Contains($Key)) {
        $Values[$Key] = $Value
    }
}

function Get-CompatiblePreset {
    param([string]$Preset)
    switch ($Preset) {
        "deepseek" {
            return @{
                name = "DeepSeek"
                baseUrl = "https://api.deepseek.com/v1"
                model = "deepseek-chat"
            }
        }
        "qwen" {
            return @{
                name = "Qwen / DashScope"
                baseUrl = "https://dashscope.aliyuncs.com/compatible-mode/v1"
                model = "qwen-plus"
            }
        }
        "siliconflow" {
            return @{
                name = "SiliconFlow"
                baseUrl = "https://api.siliconflow.cn/v1"
                model = "Qwen/Qwen2.5-7B-Instruct"
            }
        }
        default {
            return @{
                name = "Custom OpenAI-compatible"
                baseUrl = ""
                model = ""
            }
        }
    }
}

$values = Read-EnvFile $EnvExamplePath
foreach ($key in (Read-EnvFile $EnvPath).Keys) {
    $values[$key] = (Read-EnvFile $EnvPath)[$key]
}

Set-Default $values "REMOTE_API_MODE" "auto"
Set-Default $values "LLM_PROVIDER" "mock"
Set-Default $values "OPENAI_API_STYLE" "chat_completions"
Set-Default $values "OPENAI_BASE_URL" "https://api.openai.com/v1"
Set-Default $values "OPENAI_MODEL" "gpt-4.1-mini"
Set-Default $values "ANTHROPIC_BASE_URL" "https://api.anthropic.com/v1"
Set-Default $values "ANTHROPIC_MODEL" "claude-3-5-haiku-latest"
Set-Default $values "RAG_VECTOR_STORE" "chroma"
Set-Default $values "APP_CHROMA_DIR" "./data/knowledge/chroma"
Set-Default $values "RAG_EMBEDDING_PROVIDER" "openai"
Set-Default $values "OPENAI_EMBEDDING_MODEL" "text-embedding-3-small"
Set-Default $values "OPENAI_EMBEDDING_API_STYLE" "openai_compatible"
Set-Default $values "LOCAL_MULTIMODAL_BASE_URL" "http://127.0.0.1:11434/v1"
Set-Default $values "LOCAL_MULTIMODAL_MODEL" "llava:latest"
Set-Default $values "LOCAL_MULTIMODAL_API_KEY" "ollama"
Set-Default $values "LOCAL_MULTIMODAL_MAX_TOKENS" "1200"
Set-Default $values "LOCAL_MULTIMODAL_TEMPERATURE" "0.2"

if (-not $Provider) {
    Write-Host "Choose API provider mode:" -ForegroundColor Cyan
    Write-Host "  1. OpenAI-compatible /chat/completions (recommended for DeepSeek, Qwen, SiliconFlow, gateway)"
    Write-Host "  2. OpenAI official Responses API"
    Write-Host "  3. Anthropic Messages API"
    Write-Host "  4. Local multimodal vision model (Ollama / LM Studio / vLLM-compatible)"
    Write-Host "  5. Offline mock only"
    $choice = Read-DefaultedValue -Prompt "Select 1-5" -Default "1"
    $Provider = switch ($choice) {
        "2" { "openai" }
        "3" { "anthropic" }
        "4" { "local" }
        "5" { "mock" }
        default { "compatible" }
    }
}

switch ($Provider) {
    "compatible" {
        if (-not $CompatiblePreset -and -not $BaseUrl) {
            Write-Host ""
            Write-Host "Choose OpenAI-compatible preset:" -ForegroundColor Cyan
            Write-Host "  1. DeepSeek (https://api.deepseek.com/v1, deepseek-chat)"
            Write-Host "  2. Qwen / DashScope (https://dashscope.aliyuncs.com/compatible-mode/v1, qwen-plus)"
            Write-Host "  3. SiliconFlow (https://api.siliconflow.cn/v1, Qwen/Qwen2.5-7B-Instruct)"
            Write-Host "  4. Custom"
            $presetChoice = Read-DefaultedValue -Prompt "Select 1-4" -Default "1"
            $CompatiblePreset = switch ($presetChoice) {
                "2" { "qwen" }
                "3" { "siliconflow" }
                "4" { "custom" }
                default { "deepseek" }
            }
        }
        $preset = Get-CompatiblePreset -Preset $CompatiblePreset
        $values["REMOTE_API_MODE"] = "auto"
        $values["LLM_PROVIDER"] = "openai"
        $values["OPENAI_API_STYLE"] = "chat_completions"
        $defaultBaseUrl = if ($preset.baseUrl) { $preset.baseUrl } else { $values["OPENAI_BASE_URL"] }
        $defaultModel = if ($preset.model) { $preset.model } else { $values["OPENAI_MODEL"] }
        Write-Host "Using preset: $($preset.name)" -ForegroundColor DarkGreen
        $values["OPENAI_BASE_URL"] = if ($BaseUrl) { $BaseUrl } else { Read-DefaultedValue -Prompt "OpenAI-compatible base URL" -Default $defaultBaseUrl }
        $values["OPENAI_MODEL"] = if ($Model) { $Model } else { Read-DefaultedValue -Prompt "Model name" -Default $defaultModel }
        if (-not $ApiKey) {
            $ApiKey = Read-SecretValue -Prompt "API key (input hidden)"
        }
        $values["OPENAI_API_KEY"] = $ApiKey
    }
    "openai" {
        $values["REMOTE_API_MODE"] = "auto"
        $values["LLM_PROVIDER"] = "openai"
        $values["OPENAI_API_STYLE"] = "responses"
        $values["OPENAI_BASE_URL"] = if ($BaseUrl) { $BaseUrl } else { Read-DefaultedValue -Prompt "OpenAI base URL" -Default "https://api.openai.com/v1" }
        $values["OPENAI_MODEL"] = if ($Model) { $Model } else { Read-DefaultedValue -Prompt "OpenAI model" -Default $values["OPENAI_MODEL"] }
        if (-not $ApiKey) {
            $ApiKey = Read-SecretValue -Prompt "OpenAI API key (input hidden)"
        }
        $values["OPENAI_API_KEY"] = $ApiKey
    }
    "anthropic" {
        $values["REMOTE_API_MODE"] = "auto"
        $values["LLM_PROVIDER"] = "anthropic"
        $values["ANTHROPIC_BASE_URL"] = if ($BaseUrl) { $BaseUrl } else { Read-DefaultedValue -Prompt "Anthropic base URL" -Default $values["ANTHROPIC_BASE_URL"] }
        $values["ANTHROPIC_MODEL"] = if ($Model) { $Model } else { Read-DefaultedValue -Prompt "Anthropic model" -Default $values["ANTHROPIC_MODEL"] }
        if (-not $ApiKey) {
            $ApiKey = Read-SecretValue -Prompt "Anthropic API key (input hidden)"
        }
        $values["ANTHROPIC_API_KEY"] = $ApiKey
    }
    "local" {
        $values["REMOTE_API_MODE"] = "off"
        $values["MULTIMODAL_PROVIDER"] = "local"
        $values["LOCAL_MULTIMODAL_BASE_URL"] = if ($BaseUrl) { $BaseUrl } else { Read-DefaultedValue -Prompt "Local multimodal base URL" -Default $values["LOCAL_MULTIMODAL_BASE_URL"] }
        $values["LOCAL_MULTIMODAL_MODEL"] = if ($Model) { $Model } else { Read-DefaultedValue -Prompt "Local multimodal model" -Default $values["LOCAL_MULTIMODAL_MODEL"] }
        if ($ApiKey) {
            $values["LOCAL_MULTIMODAL_API_KEY"] = $ApiKey
        }
    }
    "mock" {
        $values["REMOTE_API_MODE"] = "off"
        $values["LLM_PROVIDER"] = "mock"
        $values["MULTIMODAL_PROVIDER"] = "mock"
    }
}

if ($EnableChroma) {
    $values["RAG_VECTOR_STORE"] = "chroma"
}
elseif ($DisableChroma) {
    $values["RAG_VECTOR_STORE"] = "off"
}
elseif (-not $PSBoundParameters.ContainsKey("Provider")) {
    $chroma = Read-DefaultedValue -Prompt "Enable Chroma vector retrieval? Y/n" -Default "Y"
    $values["RAG_VECTOR_STORE"] = if ($chroma -match '^(y|yes)$') { "chroma" } else { "off" }
}

Write-EnvFile -Path $EnvPath -Values $values

Write-Host ""
Write-Host "Wrote local configuration: $EnvPath" -ForegroundColor Green
Write-Host "Provider: $($values["LLM_PROVIDER"])"
Write-Host "Multimodal provider: $($values["MULTIMODAL_PROVIDER"])"
Write-Host "Remote mode: $($values["REMOTE_API_MODE"])"
Write-Host "OpenAI API style: $($values["OPENAI_API_STYLE"])"
Write-Host "Chroma: $($values["RAG_VECTOR_STORE"])"
Write-Host "Embedding provider: $($values["RAG_EMBEDDING_PROVIDER"])"
Write-Host ""
Write-Host "The API key was written only to .env, which is ignored by Git." -ForegroundColor Yellow

if ($Validate) {
    Write-Host "Validating via local backend: http://127.0.0.1:8000/api/providers/llm/validate" -ForegroundColor Cyan
    try {
        $body = @{
            deviceModel = "发动机-示例型号 A"
            faultText = "启动困难"
            topK = 2
            provider = if ($values["LLM_PROVIDER"] -eq "anthropic") { "anthropic" } else { "openai" }
        } | ConvertTo-Json -Depth 3
        $result = Invoke-RestMethod -Method Post -Uri "http://127.0.0.1:8000/api/providers/llm/validate" -ContentType "application/json; charset=utf-8" -Body $body
        $result | ConvertTo-Json -Depth 8
    }
    catch {
        Write-Host "Validation request failed. Start the backend first, then retry with -Validate." -ForegroundColor Yellow
        Write-Host $_.Exception.Message
    }
}
