"""M0-owned stable error-code registry for the versioned HTTP contract."""

from __future__ import annotations


class ErrorCode:
    HTTP_ERROR = "HTTP_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    FORBIDDEN = "FORBIDDEN"
    IDEMPOTENCY_KEY_REQUIRED = "IDEMPOTENCY_KEY_REQUIRED"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    REQUEST_IN_PROGRESS = "REQUEST_IN_PROGRESS"
    VERSION_CONFLICT = "VERSION_CONFLICT"

    # M1 identity and audit contract. Anonymous login deliberately emits only
    # INVALID_CREDENTIALS for account/password/lock-state failures so these
    # stable codes do not become an account-enumeration side channel.
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    ACCOUNT_DISABLED = "ACCOUNT_DISABLED"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    CSRF_INVALID = "CSRF_INVALID"
    SELF_REVIEW_FORBIDDEN = "SELF_REVIEW_FORBIDDEN"
    LAST_ADMIN_PROTECTED = "LAST_ADMIN_PROTECTED"
    PASSWORD_POLICY_VIOLATION = "PASSWORD_POLICY_VIOLATION"
    AUTH_MODE_UNAVAILABLE = "AUTH_MODE_UNAVAILABLE"
